-- Core tables

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  full_name text,
  role text NOT NULL CHECK (role = ANY (ARRAY['client','coach','doctor','admin'])),
  timezone text DEFAULT 'UTC',
  created_at timestamptz DEFAULT now(),
  email text,
  avatar_url text,
  bio text,
  specialization text,
  phone text,
  locale text DEFAULT 'en',
  is_active boolean DEFAULT true,
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE public.programs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  provider_id uuid NOT NULL REFERENCES public.profiles(id),
  provider_type text NOT NULL CHECK (provider_type = ANY (ARRAY['coach','doctor'])),
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active'
    CHECK (status = ANY (ARRAY['active','completed','paused','canceled'])),
  start_date date,
  end_date date,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  provider_id uuid NOT NULL REFERENCES public.profiles(id),
  provider_type text NOT NULL CHECK (provider_type = ANY (ARRAY['coach','doctor'])),
  scheduled_at timestamptz NOT NULL,
  duration_minutes int NOT NULL DEFAULT 60,
  status text NOT NULL CHECK (status = ANY (ARRAY['scheduled','completed','canceled'])),
  created_at timestamptz DEFAULT now(),
  program_id bigint REFERENCES public.programs(id),
  session_type text NOT NULL DEFAULT 'standard',
  mode text NOT NULL DEFAULT 'online',
  price_cents int,
  currency text DEFAULT 'EUR',
  canceled_reason text,
  client_rating int CHECK (client_rating >= 1 AND client_rating <= 5),
  client_feedback text
);

CREATE TABLE public.goals (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  program_id bigint REFERENCES public.programs(id),
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active'
    CHECK (status = ANY (ARRAY['active','achieved','dropped'])),
  target_date date,
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.action_items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  session_id bigint REFERENCES public.sessions(id),
  goal_id bigint REFERENCES public.goals(id),
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  title text NOT NULL,
  description text,
  due_date date,
  status text NOT NULL DEFAULT 'open'
    CHECK (status = ANY (ARRAY['open','in_progress','done','canceled'])),
  created_at timestamptz DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE public.session_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL REFERENCES public.sessions(id),
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  author_id uuid NOT NULL REFERENCES public.profiles(id),
  note_text text NOT NULL,
  created_at timestamptz DEFAULT now(),
  visibility text NOT NULL DEFAULT 'private'
    CHECK (visibility = ANY (ARRAY['private','client_visible'])),
  note_type text NOT NULL DEFAULT 'general'
    CHECK (note_type = ANY (ARRAY['general','summary','homework','medical']))
);

CREATE TABLE public.client_coach_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  coach_id uuid NOT NULL REFERENCES public.profiles(id),
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.client_doctor_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  doctor_id uuid NOT NULL REFERENCES public.profiles(id),
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz DEFAULT now()
);

-- Indexes for common filters

CREATE INDEX IF NOT EXISTS profiles_role_idx
  ON public.profiles (role);

CREATE INDEX IF NOT EXISTS sessions_client_status_scheduled_idx
  ON public.sessions (client_id, status, scheduled_at);

CREATE INDEX IF NOT EXISTS sessions_provider_status_scheduled_idx
  ON public.sessions (provider_id, status, scheduled_at);

CREATE INDEX IF NOT EXISTS programs_client_status_idx
  ON public.programs (client_id, status);

CREATE INDEX IF NOT EXISTS goals_client_status_idx
  ON public.goals (client_id, status);

CREATE INDEX IF NOT EXISTS action_items_client_status_due_idx
  ON public.action_items (client_id, status, due_date);

CREATE INDEX IF NOT EXISTS client_coach_links_coach_status_idx
  ON public.client_coach_links (coach_id, status);

CREATE INDEX IF NOT EXISTS client_doctor_links_doctor_status_idx
  ON public.client_doctor_links (doctor_id, status);
